'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        'dashboard': 'Dashboard',
        // Sidebar
        'inventory': 'Inventory',
        'item_inventory': 'Item Inventory',
        'sample_masters': 'Sample Masters',
        'attributes': 'Attributes',
        'item_type': 'Type',
        'categories': 'Categories',
        'locations': 'Locations',
        'sales': 'Sales',
        'procurement': 'Procurement',
        'sales_orders': 'Sales Orders',
        'customers': 'Customers',
        'suppliers': 'Suppliers',
        'purchase_orders': 'Purchase Orders',
        'sample_requests': 'Sample Requests',
        'sample_report': 'Sample Report',
        'lab_dip_report': 'Lab Dip Report',
        'engineering': 'Engineering',
        'production': 'Production',
        'warehouse': 'Warehouse',
        'bom': 'Bill of Materials',
        'production_calendar': 'Production Calendar',
        'routing': 'Routing & Ops',
        'work_orders': 'Work Orders',
        'work_queue': 'Work Queue',
        'manufacturing_orders': 'Manufacturing Orders',
        'stock_adjustment': 'Stock Adjustment',
        'stock_on_hand': 'Stock On-Hand',
        'booking_stock': 'Booking Stock',
        'location': 'Location',
        'variant': 'Variant',
        'on_hand': 'On Hand',
        'incoming': 'Incoming',
        'required': 'Required',
        'reserved': 'Reserved',
        'net_free': 'Net Free',
        'all_locations': 'All Locations',
        'demand_from_mos': 'Required by',
        'incoming_from_mos': 'Incoming from',
        'reserved_by_sos': 'Reserved by',
        'how_calculated': 'How is this calculated?',
        'how_booking_stock_calculated': 'How is Booking Stock calculated?',
        'reports': 'Reports',
        'stock_ledger': 'Stock Ledger',
        'machine_report': 'Production Output',
        'administration': 'Administration',
        'print_designer': 'Print Layouts',
        'settings': 'Settings',
        'scanner': 'Scanner',
        'login': 'Login',
        'account_settings': 'Account Settings',

        // Dashboard
        'smart_advisor': 'Smart Advisor',
        'warehouse_distribution': 'Warehouse Distribution',
        'production_deadlines': 'Production Deadlines',
        'recent_activity': 'Recent Activity',
        'manufacturing_monitoring': 'Manufacturing Monitoring',
        'kpi_trends': 'KPI Trends (30 days)',
        'recent_stock_movements': 'Recent Stock Movements',
        'work_order_monitoring': 'Work Order Monitoring',
        'action_items': 'Action Items',
        'system_status': 'System Status',
        'stock_health': 'Stock Health',
        'production_health': 'Production Health',
        'order_health': 'Order Health',
        'production_yield': 'Production Yield',
        'delivery_readiness': 'Delivery Readiness',
        'low_stock': 'Low Stock',
        'active_wo': 'Active WO',
        'pending_wo': 'Pending WO',
        'samples': 'Samples',
        'open_orders': 'Open Orders',
        'delivery_outlook': 'Delivery Outlook',
        'customer': 'Customer',
        'shippable': 'Shippable',
        'no_open_orders': 'No open sales orders',
        'late_orders': 'Late',
        'at_risk': 'At Risk',
        'ready_to_ship': 'Ready',
        'stock_risk': 'Stock Risk',
        'no_low_stock': 'Nothing below its reorder point',
        'below_reorder': 'below reorder',
        'out_of_stock': 'out',
        'total_skus': 'Total SKUs',
        'product': 'Product',
        'progress': 'Progress',
        'target': 'Target',
        'change': 'Change',
        'item': 'Item',
        'when': 'When',
        'code': 'Code',
        'reference': 'Reference',
        'system_balanced': 'System state is currently balanced.',
        'all_systems_nominal': 'All systems nominal',
        'no_inventory_recorded': 'No inventory recorded',
        'no_recent_movements': 'No recent movements',
        'no_active_production': 'No active production runs',
        'require_replenishment': 'require replenishment',
        'ready_for_release': 'ready for release',
        'material_shortages_affecting': 'Material shortages affecting',
        'of_orders': 'of orders',
        'view_details': 'View details',

        // Common
        'create': 'Create',
        'save': 'Save',
        'delete': 'Delete',
        'cancel': 'Cancel',
        'edit': 'Edit',
        'add': 'Add',
        'refresh': 'Refresh',
        'print': 'Print',
        'search': 'Search',
        'actions': 'Actions',
        'status': 'Status',
        'logout': 'Logout',
        'qty': 'Qty',
        'date': 'Date',
        'from': 'From',
        'to': 'To',
        
        // Locations
        'location_code': 'Code',
        'location_name': 'Name',

        // Items
        'item_code': 'Item Code',
        'item_name': 'Item Name',
        'uom': 'UOM',
        'source_sample': 'Source Sample',
        'weight_per_unit': 'Weight / Unit',
        
        // Manufacturing
        'production_schedule': 'Production Schedule',
        'new_production_run': 'New Production Run',
        'select_recipe': 'Select Recipe',
        'production_location': 'Production Location',
        'due_date': 'Due Date',
        'start': 'Start',
        'finish': 'Finish',
        'pending': 'PENDING',
        'in_progress': 'IN PROGRESS',
        'completed': 'COMPLETED',
        'cancelled': 'CANCELLED',
        
        // BOM
        'active_boms': 'Active BOMs',
        'create_recipe': 'Create Recipe',
        'finished_good': 'Finished Good',
        'materials': 'Materials',
        'routing_operations': 'Routing & Operations',
        
        // Routing
        'work_centers': 'Work Centers',
        'standard_operations': 'Standard Operations',
        'station_name': 'Station Name',
        'operation_name': 'Operation Name',
        
        // Work-center performance monitor
        'performance_monitor': 'Performance Monitor',
        'performance': 'Performance',
        'work_calendar': 'Calendar',
        // Warp beams belong to the loom, not to a work order: mounted once, shared
        // by every WO that runs on the machine, counted in whole pieces.
        'beams_on_loom': 'Beams',
        'beam_loom_hint': 'A mounted warp belongs to this machine and feeds every work order that runs on it — size S, then M, then L. It is mounted once, not re-staged per size.',
        'beam_positions_filled': 'beam positions filled',
        'no_beams_mounted': 'No warp mounted on this machine.',
        'warp_mounted': 'Warp',
        'pcs': 'pcs',
        'dismount': 'Unmount',
        'dismount_hint': 'Take this beam off the loom. The remnant keeps its own lot.',
        'unmount_remnant_to': 'remnant returns to',
        'unmount_leave_at_loom': '— leave parked at the machine —',
        'unmount_confirm': 'Unmount',
        'unmount_done': 'Beam unmounted.',
        'unmount_failed': 'Could not unmount beam.',
        // Leftover warp: every dismount strips the remnant off the beam and
        // weighs it, then it becomes its own lot any loom can mount later.
        'leftover_hint': 'Weigh the warp taken off the beam. It becomes its own leftover lot; this beam is retired at 0 and any difference against the system figure is written off on it.',
        'leftover_weighed_qty': 'Weighed leftover (kg)',
        'leftover_lot_no': 'Leftover lot no.',
        'leftover_lot_auto': 'Auto (LFT-…)',
        'leftover_system_says': 'System says',
        'leftover_variance': 'Variance',
        'leftover_created': 'Leftover lot {lot} created ({qty} kg).',
        'mount_beam': 'Mount Beam',
        'mount_beam_hint': 'Put a beam up on this machine. Leftover lots stripped off earlier warps can go back up here.',
        'mount_beam_search': 'Scan or search lot / item...',
        'no_free_beams': 'No free beams in stock.',
        'scan_beam': 'Use Camera',
        'scan_beam_stop': 'Stop Camera',
        'scan_beam_hint': 'Scan a beam label to mount it straight away.',
        'leftover_tag': 'Leftover',
        'mount_done': 'Beam mounted.',
        'mount_failed': 'Could not mount beam.',
        'mount_confirm': 'Mount',
        'beam_slots_full': 'All beam positions are filled.',
        'lot': 'Lot',
        'ends': 'Ends',
        'remaining': 'Remaining',
        'mounted': 'Mounted',
        'no_active_run': 'No active run on this machine.',
        'start_run': 'Start Run',
        'stop_run': 'Stop',
        'pause_run': 'Pause',
        'resume_run': 'Resume',
        'paused': 'Paused',
        'paused_days_excluded': 'Paused days excluded',
        'pause_failed': 'Could not pause this run.',
        'resume_failed': 'Could not resume this run.',
        'manufacturing_order': 'Manufacturing Order',
        'lines': 'Lines',
        'rate_per_line': 'g/min/line',
        'target_efficiency': 'Target Eff %',
        'start_date': 'Start Date',
        'target_100_day': 'Target 100%/day',
        'elapsed_days': 'Working days',
        'theoretical_100': 'Theoretical 100%',
        'actual_produced': 'Actual produced',
        'manual': 'manual',
        'efficiency': 'Efficiency',
        'on_target': 'on target',
        'below_target': 'below target',
        'actual_rate': 'Actual rate',
        'mo_completion': 'MO Completion Projection',
        'target_qty': 'Target qty',
        'total_actual': 'Total actual',
        'combined_target_rate': 'Combined target/day',
        'target_working_days': 'Target working days',
        'target_completion': 'Target completion',
        'projected_completion': 'Projected completion',
        'machines_on_mo': 'Machines on this MO',
        // Completion-date warning: the WO's own promised end date vs where the rate
        // actually being achieved lands.
        'wo_due': 'WO due date',
        'late_warning': 'Projected to finish late by',
        'late_basis_wo': 'WO target end date',
        'late_basis_plan': 'planned completion',
        'late_action_hint': 'Add a machine or add working days to recover.',
        'late_by': 'Late by',
        'not_achievable': 'Not achievable',
        'no_output_yet': 'No output logged — the order cannot be met at the current rate',
        'behind_schedule': 'behind schedule',
        'days': 'days',
        'wo_short': 'WO',
        'running_only': 'Running only',
        'running_only_hint': 'Show only looms with an active run',
        'no_running_machines': 'No loom is running right now.',
        'prev_run': 'Previous WO',
        'next_run': 'Next WO',
        'start_another_run': 'Start another WO',
        'rate_from_first_run': "g/min/line and target % follow the loom's first run",
        'rate_overridden': 'g/min/line and target % overridden for this WO',
        'rate_edit': 'change',
        'rate_reset': 'use loom values',
        'work_order': 'Work Order',
        'no_wo_on_machine': 'No open WO on this machine',
        'available': 'available',
        'already_running': 'already running here',
        'pick_wo_instead': 'pick a WO instead',
        'pick_mo_instead': 'pick an MO instead',
        'run_history': 'Run History',
        'actual': 'Actual',
        'end': 'End',
        'working_days': 'Working Days',
        'working_days_hint': 'Days this machine runs. The working-day count and completion-date projection skip un-checked weekdays and the holidays below.',
        'holidays': 'Holidays',
        'note': 'Note',
        'no_holidays': 'No holidays set.',
        'targets': 'Targets',
        'weaving_monitor': 'Weaving Monitor',
        // Dyeing monitor. A vessel is measured in yards against reel speed, not in
        // kg against a calendar, so it carries its own vocabulary.
        'dyeing_monitor': 'Dyeing Monitor',
        'loaded': 'loaded',
        'yards_dyed': 'Dyed',
        'yd_per_min': 'yd/min',
        'yd_short': 'yd',
        'elapsed': 'Elapsed',
        'run_time': 'Run',
        'no_dyeing_machines': 'No dyeing machines configured.',
        'no_active_batch': 'No active batch',
        'batch_loaded_hint': 'Loaded, waiting to start.',
        'needs_setup': 'need setup',
        // Dye batch phases: match -> start -> complete, each stamped on the floor.
        'color_matching': 'Color matching',
        'batch_matching_hint': 'Shade being matched at the vessel — not dyeing yet.',
        'phase_match': 'Match',
        'phase_start': 'Start',
        'phase_complete': 'Done',
        'phase_prep_gap': 'Time spent matching the shade, before the machine started.',
        'phase_run_gap': 'Time on the machine — the window efficiency is measured over.',
        'start_color_matching': 'Color matching',
        'start_batch': 'Start',
        'complete_batch': 'Complete',
        'phase_failed': 'Could not record that step',
        'no_speed_picked': 'No speed picked',
        'no_speed_picked_hint': 'Pick this batch’s yd/min with Set rate to report efficiency.',
        'no_lines_set': 'No lines set',
        'speed_preset_hint': 'Curated on the Attributes page (Dyeing Speed).',
        'or_type_speed': 'or type',
        'no_speed_presets': 'No speeds curated yet',
        'custom': 'custom',
        'no_gy_factor': 'No g/y on the item',
        'no_gy_factor_hint': 'Yards cannot be derived from this item’s stock unit.',
        'set_rate': 'Set rate',
        'rate_saved': 'Rate updated',
        'rate_failed': 'Could not update the rate',
        'machines': 'machines',
        'running': 'running',
        'idle': 'idle',
        // Loom prep walk: staged (warp up) → draw-in → tuning → start.
        'staged': 'staged',
        'draw_in': 'Draw-in',
        'tuning': 'Tuning',
        'loom_prep': 'Loom Preparation',
        'loom_prep_hint': 'Warp is up. Confirm Draw-in, then Tuning, before starting the run.',
        'prep_reset': 'Undo step',
        'prep_blocked_start': 'Finish Draw-in and Tuning before starting the run.',
        'prep_failed': 'Could not change loom step.',
        'avg_efficiency': 'Avg efficiency',
        'loading': 'Loading...',
        'no_weaving_machines': 'No weaving machines defined. Add machines with type WEAVING in Routing.',
        'click_for_detail': 'Click for detail',
        'import_id_holidays': 'Import holidays',
        'today': 'Today',
        'working_day': 'Working day',
        'rest_day': 'Rest day',
        'national_holiday': 'National holiday',
        'holiday': 'Holiday',
        'click_to_add': 'click to add',
        'calendar_click_hint': 'Click a day to mark / unmark it as a holiday for this machine. ★ = Indonesian national holiday.',
        'all': 'All',
        'group': 'Group',
        'import': 'Import',
        'remove': 'Remove',
        'saving': 'Saving',
        'replace_holidays_on_machines': 'Also replace holidays on every machine',
        'machines_to_update': 'Machines that will be updated',
        'no_machines_in_group': 'No machines under this group yet',
        'apply_to': 'Apply to',
        // Sales order fulfilment
        'so_no_weight': 'no weight',
        'so_no_weight_hint': 'This item is stocked by weight but has no weight per yard on its item master, so the ordered yardage cannot be converted. Set Weight per unit on the item to see fulfilment progress.',
        // Headers
        'powered_by': 'Powered by',
    },
    id: {
        'dashboard': 'Dasbor',
        // Sidebar
        'inventory': 'Inventaris',
        'item_inventory': 'Daftar Barang',
        'sample_masters': 'Master Sampel',
        'attributes': 'Atribut',
        'item_type': 'Tipe',
        'categories': 'Kategori',
        'locations': 'Lokasi',
        'sales': 'Penjualan',
        'procurement': 'Pengadaan',
        'sales_orders': 'Pesanan Penjualan',
        'customers': 'Pelanggan',
        'suppliers': 'Pemasok',
        'purchase_orders': 'Pesanan Pembelian',
        'sample_requests': 'Permintaan Sampel',
        'sample_report': 'Laporan Sampel',
        'lab_dip_report': 'Laporan Lab Dip',
        'engineering': 'Teknik',
        'production': 'Produksi',
        'warehouse': 'Gudang',
        'bom': 'Resep Produksi (BOM)',
        'production_calendar': 'Kalender Produksi',
        'work_orders': 'Perintah Kerja (WO)',
        'work_queue': 'Antrian Kerja',
        'manufacturing_orders': 'Perintah Produksi (MO)',
        'routing': 'Routing & Operasi',
        'stock_adjustment': 'Penyesuaian Stok',
        'stock_on_hand': 'Stok Tersedia',
        'booking_stock': 'Stok Booking',
        'location': 'Lokasi',
        'variant': 'Varian',
        'on_hand': 'Tersedia',
        'incoming': 'Masuk',
        'required': 'Dibutuhkan',
        'reserved': 'Dipesan',
        'net_free': 'Sisa Bebas',
        'all_locations': 'Semua Lokasi',
        'demand_from_mos': 'Dibutuhkan oleh',
        'incoming_from_mos': 'Masuk dari',
        'reserved_by_sos': 'Dipesan oleh',
        'how_calculated': 'Bagaimana ini dihitung?',
        'how_booking_stock_calculated': 'Bagaimana Stok Booking dihitung?',
        'reports': 'Laporan',
        'stock_ledger': 'Buku Besar Stok',
        'machine_report': 'Hasil Produksi',
        'administration': 'Administrasi',
        'print_designer': 'Tata Letak Cetak',
        'settings': 'Pengaturan',
        'scanner': 'Pemindai',
        'login': 'Masuk',
        'account_settings': 'Pengaturan Akun',

        // Dashboard
        'smart_advisor': 'Penasihat Cerdas',
        'warehouse_distribution': 'Distribusi Gudang',
        'production_deadlines': 'Tenggat Produksi',
        'recent_activity': 'Aktivitas Terkini',
        'manufacturing_monitoring': 'Pemantauan Produksi',
        'kpi_trends': 'Tren KPI (30 hari)',
        'recent_stock_movements': 'Pergerakan Stok Terkini',
        'work_order_monitoring': 'Pemantauan Perintah Kerja',
        'action_items': 'Daftar Tindakan',
        'system_status': 'Status Sistem',
        'stock_health': 'Kesehatan Stok',
        'production_health': 'Kesehatan Produksi',
        'order_health': 'Kesehatan Pesanan',
        'production_yield': 'Hasil Produksi',
        'delivery_readiness': 'Kesiapan Pengiriman',
        'low_stock': 'Stok Rendah',
        'active_wo': 'WO Aktif',
        'pending_wo': 'WO Tertunda',
        'samples': 'Sampel',
        'open_orders': 'Pesanan Terbuka',
        'delivery_outlook': 'Prospek Pengiriman',
        'customer': 'Pelanggan',
        'shippable': 'Siap Kirim',
        'no_open_orders': 'Tidak ada pesanan terbuka',
        'late_orders': 'Terlambat',
        'at_risk': 'Berisiko',
        'ready_to_ship': 'Siap',
        'stock_risk': 'Risiko Stok',
        'no_low_stock': 'Tidak ada item di bawah titik pesan ulang',
        'below_reorder': 'di bawah titik pesan',
        'out_of_stock': 'habis',
        'total_skus': 'Total SKU',
        'product': 'Produk',
        'progress': 'Progres',
        'target': 'Target',
        'change': 'Perubahan',
        'item': 'Barang',
        'when': 'Waktu',
        'code': 'Kode',
        'reference': 'Referensi',
        'system_balanced': 'Kondisi sistem saat ini seimbang.',
        'all_systems_nominal': 'Semua sistem normal',
        'no_inventory_recorded': 'Tidak ada inventaris tercatat',
        'no_recent_movements': 'Tidak ada pergerakan terkini',
        'no_active_production': 'Tidak ada produksi aktif',
        'require_replenishment': 'perlu pengisian ulang',
        'ready_for_release': 'siap dirilis',
        'material_shortages_affecting': 'Kekurangan material memengaruhi',
        'of_orders': 'dari pesanan',
        'view_details': 'Lihat detail',

        // Common
        'create': 'Buat',
        'save': 'Simpan',
        'delete': 'Hapus',
        'cancel': 'Batal',
        'edit': 'Ubah',
        'add': 'Tambah',
        'refresh': 'Segarkan',
        'print': 'Cetak',
        'search': 'Cari',
        'actions': 'Aksi',
        'status': 'Status',
        'logout': 'Keluar',
        'qty': 'Jml',
        'date': 'Tanggal',
        'from': 'Dari',
        'to': 'Sampai',
        
        // Locations
        'location_code': 'Kode',
        'location_name': 'Nama',

        // Items
        'item_code': 'Kode Barang',
        'item_name': 'Nama Barang',
        'uom': 'Satuan',
        'source_sample': 'Sampel Sumber',
        'weight_per_unit': 'Berat / Satuan',
        
        // Manufacturing
        'production_schedule': 'Jadwal Produksi',
        'new_production_run': 'Jalan Produksi Baru',
        'select_recipe': 'Pilih Resep',
        'production_location': 'Lokasi Produksi',
        'due_date': 'Tenggat Waktu',
        'start': 'Mulai',
        'finish': 'Selesai',
        'pending': 'TUNDA',
        'in_progress': 'DIPROSES',
        'completed': 'SELESAI',
        'cancelled': 'BATAL',
        
        // BOM
        'active_boms': 'Daftar Resep Aktif',
        'create_recipe': 'Buat Resep',
        'finished_good': 'Barang Jadi',
        'materials': 'Bahan Baku',
        'routing_operations': 'Alur & Operasi',
        
        // Routing
        'work_centers': 'Pusat Kerja (Stasiun)',
        'standard_operations': 'Operasi Standar',
        'station_name': 'Nama Stasiun',
        'operation_name': 'Nama Operasi',
        
        // Work-center performance monitor
        'performance_monitor': 'Monitor Performa',
        'performance': 'Performa',
        'work_calendar': 'Kalender',
        'beams_on_loom': 'Beam',
        'beam_loom_hint': 'Beam yang sudah naik milik mesin ini dan dipakai semua work order yang jalan di mesin ini — size S, lalu M, lalu L. Naik sekali saja, tidak perlu stage ulang per size.',
        'beam_positions_filled': 'posisi beam terisi',
        'no_beams_mounted': 'Belum ada beam yang naik di mesin ini.',
        'warp_mounted': 'Beam',
        'pcs': 'pcs',
        'dismount': 'Turunkan',
        'dismount_hint': 'Turunkan beam dari mesin. Sisa beam tetap memakai lot-nya sendiri.',
        'unmount_remnant_to': 'sisa dikembalikan ke',
        'unmount_leave_at_loom': '— biarkan tetap di mesin —',
        'unmount_confirm': 'Turunkan',
        'unmount_done': 'Beam sudah diturunkan.',
        'unmount_failed': 'Gagal menurunkan beam.',
        'leftover_hint': 'Timbang sisa benang yang diturunkan dari beam. Sisa jadi lot sendiri; beam ini ditutup di 0 dan selisih dengan angka sistem dibebankan ke beam ini.',
        'leftover_weighed_qty': 'Sisa timbang (kg)',
        'leftover_lot_no': 'No. lot sisa',
        'leftover_lot_auto': 'Otomatis (LFT-…)',
        'leftover_system_says': 'Menurut sistem',
        'leftover_variance': 'Selisih',
        'leftover_created': 'Lot sisa {lot} dibuat ({qty} kg).',
        'mount_beam': 'Naikkan Beam',
        'mount_beam_hint': 'Naikkan beam ke mesin ini. Lot sisa dari beam sebelumnya bisa dinaikkan lagi di sini.',
        'mount_beam_search': 'Scan atau cari lot / item...',
        'no_free_beams': 'Tidak ada beam bebas di stok.',
        'scan_beam': 'Pakai Kamera',
        'scan_beam_stop': 'Stop Kamera',
        'scan_beam_hint': 'Scan label beam untuk langsung menaikkannya.',
        'leftover_tag': 'Sisa',
        'mount_done': 'Beam sudah dinaikkan.',
        'mount_failed': 'Gagal menaikkan beam.',
        'mount_confirm': 'Naikkan',
        'beam_slots_full': 'Semua posisi beam sudah terisi.',
        'lot': 'Lot',
        'ends': 'Utas',
        'remaining': 'Sisa',
        'mounted': 'Naik',
        'no_active_run': 'Tidak ada run aktif di mesin ini.',
        'start_run': 'Mulai Run',
        'stop_run': 'Stop',
        'pause_run': 'Jeda',
        'resume_run': 'Lanjut',
        'paused': 'Dijeda',
        'paused_days_excluded': 'Hari jeda tidak dihitung',
        'pause_failed': 'Run ini tidak dapat dijeda.',
        'resume_failed': 'Run ini tidak dapat dilanjutkan.',
        'manufacturing_order': 'Manufacturing Order',
        'lines': 'Line',
        'rate_per_line': 'gr/menit/line',
        'target_efficiency': 'Target Efisiensi %',
        'start_date': 'Tanggal Mulai',
        'target_100_day': 'Target 100%/hari',
        'elapsed_days': 'Hari kerja',
        'theoretical_100': 'Teoritis 100%',
        'actual_produced': 'Hasil aktual',
        'manual': 'manual',
        'efficiency': 'Efisiensi',
        'on_target': 'capai target',
        'below_target': 'di bawah target',
        'actual_rate': 'Laju aktual',
        'mo_completion': 'Proyeksi Penyelesaian MO',
        'target_qty': 'Target qty',
        'total_actual': 'Total aktual',
        'combined_target_rate': 'Target gabungan/hari',
        'target_working_days': 'Target hari kerja',
        'target_completion': 'Target selesai',
        'projected_completion': 'Proyeksi selesai',
        'machines_on_mo': 'Mesin pada MO ini',
        'wo_due': 'Tgl target selesai WO',
        'late_warning': 'Proyeksi terlambat',
        'late_basis_wo': 'target selesai WO',
        'late_basis_plan': 'rencana selesai',
        'late_action_hint': 'Tambah mesin atau tambah hari kerja.',
        'late_by': 'Terlambat',
        'not_achievable': 'Tidak tercapai',
        'no_output_yet': 'Belum ada hasil dicatat — target tidak tercapai dengan kecepatan saat ini',
        'behind_schedule': 'terlambat',
        'days': 'hari',
        'wo_short': 'WO',
        'running_only': 'Hanya berjalan',
        'running_only_hint': 'Tampilkan hanya mesin dengan run aktif',
        'no_running_machines': 'Tidak ada mesin yang berjalan saat ini.',
        'prev_run': 'WO sebelumnya',
        'next_run': 'WO berikutnya',
        'start_another_run': 'Jalankan WO lain',
        'rate_from_first_run': 'gr/menit/line dan target % mengikuti run pertama mesin',
        'rate_overridden': 'gr/menit/line dan target % diubah khusus WO ini',
        'rate_edit': 'ubah',
        'rate_reset': 'pakai nilai mesin',
        'work_order': 'Perintah Kerja (WO)',
        'no_wo_on_machine': 'Tidak ada WO terbuka di mesin ini',
        'available': 'tersedia',
        'already_running': 'sedang jalan di sini',
        'pick_wo_instead': 'pilih WO saja',
        'pick_mo_instead': 'pilih MO saja',
        'run_history': 'Riwayat Run',
        'actual': 'Aktual',
        'end': 'Selesai',
        'working_days': 'Hari Kerja',
        'working_days_hint': 'Hari mesin ini berjalan. Hitungan hari kerja dan proyeksi tanggal selesai mengabaikan hari yang tidak dicentang dan hari libur di bawah.',
        'holidays': 'Hari Libur',
        'note': 'Catatan',
        'no_holidays': 'Belum ada hari libur.',
        'targets': 'Target',
        'weaving_monitor': 'Monitor Tenun',
        'dyeing_monitor': 'Monitor Celup',
        'loaded': 'terisi',
        'yards_dyed': 'Tercelup',
        'yd_per_min': 'yd/mnt',
        'yd_short': 'yd',
        'elapsed': 'Berjalan',
        'run_time': 'Proses',
        'no_dyeing_machines': 'Belum ada mesin celup.',
        'no_active_batch': 'Tidak ada proses berjalan',
        'batch_loaded_hint': 'Sudah terisi, menunggu mulai.',
        'needs_setup': 'perlu setelan',
        'color_matching': 'Matching warna',
        'batch_matching_hint': 'Warna sedang di-matching di mesin — belum mencelup.',
        'phase_match': 'Matching',
        'phase_start': 'Mulai',
        'phase_complete': 'Selesai',
        'phase_prep_gap': 'Lama matching warna, sebelum mesin jalan.',
        'phase_run_gap': 'Lama di mesin — rentang yang dipakai menghitung efisiensi.',
        'start_color_matching': 'Matching warna',
        'start_batch': 'Mulai',
        'complete_batch': 'Selesai',
        'phase_failed': 'Gagal mencatat tahap itu',
        'no_speed_picked': 'Kecepatan belum dipilih',
        'no_speed_picked_hint': 'Pilih yd/mnt batch ini lewat Atur rate agar efisiensi terhitung.',
        'no_lines_set': 'Jumlah line belum diisi',
        'speed_preset_hint': 'Dikelola di halaman Attributes (Dyeing Speed).',
        'or_type_speed': 'atau ketik',
        'no_speed_presets': 'Belum ada daftar kecepatan',
        'custom': 'manual',
        'no_gy_factor': 'Item tidak punya g/y',
        'no_gy_factor_hint': 'Yard tidak bisa dihitung dari satuan stok item ini.',
        'set_rate': 'Atur rate',
        'rate_saved': 'Rate diperbarui',
        'rate_failed': 'Gagal memperbarui rate',
        'machines': 'mesin',
        'running': 'jalan',
        'idle': 'idle',
        'staged': 'staged',
        'draw_in': 'Draw-in',
        'tuning': 'Tuning',
        'loom_prep': 'Persiapan Mesin',
        'loom_prep_hint': 'Beam sudah naik. Konfirmasi Draw-in, lalu Tuning, sebelum Start run.',
        'prep_reset': 'Batalkan tahap',
        'prep_blocked_start': 'Selesaikan Draw-in dan Tuning sebelum Start run.',
        'prep_failed': 'Gagal mengubah tahap mesin.',
        'avg_efficiency': 'Rata-rata efisiensi',
        'loading': 'Memuat...',
        'no_weaving_machines': 'Belum ada mesin tenun. Tambah mesin tipe WEAVING di Routing.',
        'click_for_detail': 'Klik untuk detail',
        'import_id_holidays': 'Impor libur',
        'today': 'Hari ini',
        'working_day': 'Hari kerja',
        'rest_day': 'Libur mingguan',
        'national_holiday': 'Libur nasional',
        'holiday': 'Libur',
        'click_to_add': 'klik untuk tambah',
        'calendar_click_hint': 'Klik tanggal untuk menandai / membatalkan hari libur mesin ini. ★ = libur nasional Indonesia.',
        'all': 'Semua',
        'group': 'Grup',
        'import': 'Impor',
        'remove': 'Hapus',
        'saving': 'Menyimpan',
        'replace_holidays_on_machines': 'Ganti juga hari libur di semua mesin',
        'machines_to_update': 'Mesin yang akan diperbarui',
        'no_machines_in_group': 'Belum ada mesin di grup ini',
        'apply_to': 'Terapkan ke',
        // Sales order fulfilment
        'so_no_weight': 'tanpa berat',
        'so_no_weight_hint': 'Barang ini disimpan dalam satuan berat tetapi tidak punya berat per yard di master barang, jadi yardage pesanan tidak bisa dikonversi. Isi Berat per unit di barang untuk melihat progres pemenuhan.',
        // Headers
        'powered_by': 'Ditenagai oleh',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('app_language') as Language;
        if (savedLang && (savedLang === 'en' || savedLang === 'id')) {
            setLanguage(savedLang);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations['en']] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
