"""Build the schema on an empty database.

`alembic upgrade head` cannot: the baseline revision (badce8f1a27f) is an
ALTER/index diff autogenerated against the legacy DB, with no `create_table`.
So an empty DB gets tables from the current models, plus the objects that only
migrations create with raw SQL, and is then stamped at head (by the caller).
A migration that adds a raw-SQL object (extension, sequence, ...) must add it
here too, or fresh installs will lack it.
"""
import os

from sqlalchemy import create_engine, text

from app.db.base import Base


def bootstrap_schema(engine) -> None:
    # The colour library's GIN trigram indexes need pg_trgm before create_all.
    with engine.begin() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    Base.metadata.create_all(engine)
    # Standalone sequences aren't attached to a model, so create_all skips them.
    with engine.begin() as conn:
        for seq in ("lab_dip_request_seq", "lab_dip_yarn_request_seq"):
            conn.execute(text(f"CREATE SEQUENCE IF NOT EXISTS {seq}"))


if __name__ == "__main__":
    bootstrap_schema(create_engine(os.environ["DATABASE_URL"].replace("+asyncpg", "+psycopg2")))
